version: 2.1

orbs:
  sixrs-gke: sixriversystems/sixrs-gke@2

jobs:
  install:
    docker:
      - image: cimg/node:12.22.1
        environment:
          NODE_ENV: test
    steps:
      - checkout
      - run:
          name: npm ci
          command: |
            npm ci
      - persist_to_workspace:
          root: ./
          paths:
            - .
  publish:
    docker:
      - image: cimg/node:12.22.1
        environment:
          NODE_ENV: test
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: npm run build
          command: npm run build
      - sixrs-gke/run-release
      - run:
          name: npm publish
          command: npm publish

  # note: unused
  test-schema:
    docker:
      - image: cimg/node:12.22.1
        environment:
          NODE_ENV: test
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: npm test schema
          command: npm run test:schema

  test:
    docker:
      - image: cimg/node:12.22.1
        environment:
          NODE_ENV: test
          MOCHA_OPTS: --reporter mocha-junit-reporter --reporter-options mochaFile=./reports/junit/mocha/mocha.xml
          ESLINT_OPTS: --quiet --format junit -o ./reports/junit/eslint/eslint.xml
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: npm test
          command: npm test
      - run:
          name: npm run coverage
          command: npm run coverage
      - store_artifacts:
          path: coverage
      - store_artifacts:
          path: reports/junit/
      - store_test_results:
          path: reports/junit/

workflows:
  version: 2

  test_and_publish:
    jobs:
      - install:
          context: 6rs-public-npm
      - test:
          context: 6rs-public-npm
          requires:
            - install
      - publish:
          context: 6rs-public-npm
          requires:
            - test
